templates/shared/config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  resource :contact, only: %i[new create]

  resources :books do
    get :new2, on: :collection
  end
end

templates/shared/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new; end

  def create
    if valid_turnstile?
      redirect_to root_url, notice: 'Message sent successfully.'
    else
      redirect_to new_contact_url
    end
  end
end

templates/shared/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home; end
end

templates/shared/app/views/books/_form.html.erb
<%= form_for(book, remote: true, html: { id: turbo_form_id }) do |form| %>
  <% if book.errors.any? %>
    <ul class="error_explanation">
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <%= hidden_field_tag :turbo_form_id, turbo_form_id %>

  <p>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </p>

  <%= cloudflare_turnstile_tag data: {theme: 'dark'} %>

  <%= form.submit %>
<% end %>

templates/shared/app/views/books/create.js.erb
(function() {
    const oldForm = document.getElementById("<%= j params[:turbo_form_id] %>");
    const newFormHTML = `<%= j render(partial: 'books/form', locals: { book: @book, turbo_form_id: params[:turbo_form_id] }) %>`;

    const tempWrapper = document.createElement("div");
    tempWrapper.innerHTML = newFormHTML;
    const newForm = tempWrapper.firstElementChild;

    oldForm.replaceWith(newForm);

    const turnstileContainer = newForm.querySelector('.cf-turnstile');
    if (typeof turnstile !== "undefined" && turnstileContainer && turnstileContainer.childElementCount === 0) {
        turnstile.render(turnstileContainer);
    }
})();

templates/shared/app/views/books/new.html.erb
<p><%= notice %></p>

<h1>New Book</h1>

<%= render "form", book: @book, turbo_form_id: 'book-form' %>

templates/shared/app/views/books/new2.html.erb
<p><%= notice %></p>

<h1>New Book 1</h1>

<%= render "form", book: @book1, turbo_form_id: 'book-form1' %>

<h1>New Book 2</h1>

<%= render "form", book: @book2, turbo_form_id: 'book-form2' %>

templates/shared/app/views/contacts/new.html.erb
<h1>Contact Us</h1>

<%= form_with url: contact_path, method: :post, id: 'contact-form' do |form| %>
  <div>
    <%= form.label :message %>
    <%= form.text_area :message %>
  </div>

  <%= cloudflare_turnstile_tag %>

  <div>
    <%= form.submit 'Send Message' %>
  </div>
<% end %>

templates/shared/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cloudflare Turnstile Test App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag rescue nil %>
    <%= stylesheet_link_tag 'application', media: 'all' rescue nil %>
    <%= javascript_include_tag 'application' rescue nil %>
  </head>

  <body>
    <% if notice.present? %>
      <p id="notice"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p id="alert"><%= alert %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

templates/shared/app/views/pages/contact.html.erb
<h1>Contact Us</h1>

<%= form_with url: contact_path, method: :post, id: 'contact-form' do |form| %>
  <div>
    <%= form.label :message %>
    <%= form.text_area :message %>
  </div>

  <%= cloudflare_turnstile_tag %>

  <div>
    <%= form.submit 'Send Message' %>
  </div>
<% end %>

templates/shared/app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<%= link_to 'New Book', new_book_path %>
<br/>
<%= link_to 'Contact Us', new_contact_path %>